"""empty message

Revision ID: 358fd9327cdd
Revises: 4dabfd5a05c3
Create Date: 2019-12-04 16:02:49.664739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358fd9327cdd'
down_revision = '4dabfd5a05c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('user', sa.Column('firstname', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    op.drop_table('token')
    # ### end Alembic commands ###
